version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.2.2
jobs:
  publish:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run:
          name: npm install and build
          command: |
            npm install
            npm run build
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - run: npm publish .
  cdn:
    docker:
      - image: 'circleci/python:2.7-node'
    steps:
      - checkout
      - azure-cli/install
      - run:
          name: npm install and build
          command: |
            npm install
            npm run build
      - run:
          name: Change Name
          command: |
            cp lib/sessions.min.js session-management.js
      - run:
          name: Upload to CDN
          command: |
            bash publish.sh

workflows:
  version: 2
  publish:
    jobs:
      - publish:
          filters:
            branches:
              only: master
      - cdn:
          filters:
            branches:
              only: master
