version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.10
jobs:
  publish:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run:
          name: npm install and build
          command: |
            npm install
            npm run build
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - run: npm publish .
  cdn:
    docker:
      - image: 'circleci/python:2.7-node'
    steps:
      - checkout
      - run:
          name: npm install and build
          command: |
            npm install
            npm run build
      - run:
          name: Change Name
          command: |
            cp lib/sessions.min.js session-management.js
      - aws-s3/copy:
          from: session-management.js
          to: 's3://${BUCKET}/session-management.js'
          arguments: |
            --acl public-read

workflows:
  version: 2
  publish:
    jobs:
      - publish:
          filters:
            branches:
              only: master
      - cdn:
          filters:
            branches:
              only: master
