version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - run: npm publish .

workflows:
  version: 2
  publish:
    jobs:
      - publish:
          filters:
            branches:
              only: master
